<?php

/**
 * Implements hook_views_data_alter().
 */
function custom_module_views_data_alter(array &$data) {
    $table = 'user__' . DOMAIN_ACCESS_FIELD;

    // Current domain filter.
    $data[$table]['current'] = array(
        'title' => t('Current domain'),
        'group' => t('Domain'),
        'filter' => array(
            'field' => DOMAIN_ACCESS_FIELD . '_target_id',
            'id' => 'custom_module_domain_access_current_user_filter',
            'title' => t('User has access to current domain'),
            'help' => t('Filters out users who do not have access to current domain.'),
        ),
    );

    $table = 'media__' . DOMAIN_ACCESS_FIELD;
    $data[$table][DOMAIN_ACCESS_FIELD]['field']['id'] = 'domain_access_field';
    $data[$table][DOMAIN_ACCESS_FIELD . '_target_id']['filter']['id'] = 'domain_access_filter';
    $data[$table][DOMAIN_ACCESS_FIELD . '_target_id']['argument']['id'] = 'domain_access_argument';

    // Current domain filter.
    $data[$table]['current'] = array(
        'title' => t('Current domain'),
        'group' => t('Domain'),
        'filter' => array(
            'field' => DOMAIN_ACCESS_FIELD . '_target_id',
            'id' => 'custom_module_domain_access_current_media_filter',
            'title' => t('Available on current domain'),
            'help' => t('Filters out entities that are not available on current domain.'),
        ),
    );
}
